// Generated by CoffeeScript 2.5.1
(function() {
  var app, express, i, mockUserData, ref, v;

  express = require('express');

  app = express();

  mockUserData = [];

  ref = 'Mark Jill'.split(' ');
  for (i in ref) {
    v = ref[i];
    mockUserData[i] = {
      name: v
    };
  }

  app.get('/users', function(req, res) {
    return res.json({
      success: true,
      message: 'successfully got users. Nice!',
      users: mockUserData
    });
  });

  app.listen(8000, function() {
    return console.log('server is running');
  });

}).call(this);
