// Generated by CoffeeScript 2.5.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.listen(8000, function() {
    return console.log('server is running');
  });

}).call(this);
