// Generated by CoffeeScript 2.5.1
(function() {
  var app, express, i, mockUserData, ref, v;

  express = require('express');

  app = express();

  mockUserData = [];

  ref = 'Mark Jill'.split(' ');
  for (i in ref) {
    v = ref[i];
    mockUserData[i] = {
      name: v
    };
  }

  app.use(express.json());

  app.get('/users', function(req, res) {
    return res.json({
      success: true,
      message: 'successfully got users. Nice!',
      users: mockUserData
    });
  });

  app.get('/users/:id', function(req, res) {
    console.log(req.params.id);
    return res.json({
      success: true,
      message: 'got one user',
      user: req.params.id
    });
  });

  app.post('/login', function(req, res) {
    var mockPassword, mockUsername, password, username;
    ({username, password} = req.body);
    mockUsername = "billyTheKid";
    mockPassword = "superSecret";
    if ((username === mockUsername) && (password === mockPassword)) {
      return res.json({
        success: true,
        message: 'password and username match!',
        token: 'encrypted token goes here'
      });
    } else {
      return res.json({
        success: false,
        message: 'password and username do not match'
      });
    }
  });

  app.listen(8000, function() {
    return console.log('server is running');
  });

}).call(this);
